insert into product_types_detailed values (1, 1, 1, 'Повседневный');
insert into product_types_detailed values (2, 1, 1, 'Холистик');
insert into product_types_detailed values (3, 1, 1, 'Лечебный');
insert into product_types_detailed values (4, 1, 1, 'Для стерилизованных');
insert into product_types_detailed values (5, 1, 1, 'Гипоаллергенный');
insert into product_types_detailed values (6, 1, 1, 'Диетический');
insert into product_types_detailed values (7, 1, 1, 'Беззерновой');
insert into product_types_detailed values (8, 1, 2, 'Повседневные');
insert into product_types_detailed values (9, 1, 2, 'Холистик');
insert into product_types_detailed values (10, 1, 2, 'Лечебные');
insert into product_types_detailed values (11, 1, 2, 'Для стерилизованных');
insert into product_types_detailed values (12, 1, 2, 'Гипоаллергенные');
insert into product_types_detailed values (13, 1, 2, 'Диетические');
insert into product_types_detailed values (14, 1, 2, 'Паучи');
insert into product_types_detailed values (15, 1, 2, 'Банки-консервы');
insert into product_types_detailed values (16, 1, 4, 'Для дрессировки');
insert into product_types_detailed values (17, 1, 4, 'Для чистки зубов');
insert into product_types_detailed values (18, 1, 4, 'Колбаски');
insert into product_types_detailed values (19, 1, 4, 'Мясные/вяленые/печеные');
insert into product_types_detailed values (20, 1, 4, 'Сушеные');
insert into product_types_detailed values (21, 1, 4, 'Витамины и добавки');
insert into product_types_detailed values (22, 1, 5, 'Шампуни и бальзамы');
insert into product_types_detailed values (23, 1, 5, 'Уход за ушами');
insert into product_types_detailed values (24, 1, 5, 'Уход за глазами');
insert into product_types_detailed values (25, 1, 5, 'Уход за лапами');
insert into product_types_detailed values (26, 1, 5, 'Уход за полостью рта');
insert into product_types_detailed values (27, 1, 5, 'Уход за кожей и шерстью');
insert into product_types_detailed values (28, 1, 5, 'Гигиена');
insert into product_types_detailed values (29, 1, 5, 'Груминг');
insert into product_types_detailed values (30, 1, 6, 'Намордники');
insert into product_types_detailed values (31, 1, 6, 'Ошейники');
insert into product_types_detailed values (32, 1, 6, 'Шлейки');
insert into product_types_detailed values (33, 1, 6, 'Поводки и сворки');
insert into product_types_detailed values (34, 1, 6, 'Рулетки');
insert into product_types_detailed values (35, 1, 6, 'Цепи');
insert into product_types_detailed values (36, 1, 6, 'Карабины, вертлюги');
insert into product_types_detailed values (37, 1, 7, 'Металлические');
insert into product_types_detailed values (38, 1, 7, 'Керамические');
insert into product_types_detailed values (39, 1, 7, 'Пластиковые');
insert into product_types_detailed values (40, 1, 7, 'На подставке');
insert into product_types_detailed values (41, 1, 7, 'Автопоилки и автокормушки');
insert into product_types_detailed values (42, 1, 8, 'Мячи');
insert into product_types_detailed values (43, 1, 8, 'Фрисби');
insert into product_types_detailed values (44, 1, 8, 'Канатные');
insert into product_types_detailed values (45, 1, 8, 'Мягкие');
insert into product_types_detailed values (46, 1, 8, 'Кольца');
insert into product_types_detailed values (47, 1, 8, 'Кости');
insert into product_types_detailed values (48, 1, 8, 'Резиновые, латексные');
insert into product_types_detailed values (49, 1, 9, 'Куртки');
insert into product_types_detailed values (50, 1, 9, 'Жилеты');
insert into product_types_detailed values (51, 1, 9, 'Свитера и толстовки');
insert into product_types_detailed values (52, 1, 9, 'Комбинезоны, дождевики');
insert into product_types_detailed values (53, 1, 11, 'Лежаки');
insert into product_types_detailed values (54, 1, 11, 'Домики');
insert into product_types_detailed values (55, 1, 11, 'Матрасы');
insert into product_types_detailed values (56, 1, 13, 'Переноски');
insert into product_types_detailed values (57, 1, 13, 'Сумки и рюкзаки');
insert into product_types_detailed values (58, 1, 13, 'Аксессуары для перевозки');
insert into product_types_detailed values (59, 1, 14, 'Средства от паразитов');
insert into product_types_detailed values (60, 1, 14, 'Для глаз');
insert into product_types_detailed values (61, 1, 14, 'Для ушей');
insert into product_types_detailed values (62, 1, 14, 'Для опорно-двигательного аппарата');
insert into product_types_detailed values (63, 1, 14, 'Ветеринарные аксессуары');
insert into product_types_detailed values (64, 2, 16, 'Повседневный');
insert into product_types_detailed values (65, 2, 16, 'Лечебный');
insert into product_types_detailed values (66, 2, 16, 'Холистик');
insert into product_types_detailed values (67, 2, 16, 'Для стерилизованных');
insert into product_types_detailed values (68, 2, 16, 'Гипоаллергенный');
insert into product_types_detailed values (69, 2, 16, 'Диетический');
insert into product_types_detailed values (70, 2, 16, 'Беззерновой');
insert into product_types_detailed values (71, 2, 17, 'Повседневные');
insert into product_types_detailed values (72, 2, 17, 'Лечебные');
insert into product_types_detailed values (73, 2, 17, 'Холистик');
insert into product_types_detailed values (74, 2, 17, 'Для стерилизованных');
insert into product_types_detailed values (75, 2, 17, 'Гипоаллергенные');
insert into product_types_detailed values (76, 2, 17, 'Диетические');
insert into product_types_detailed values (77, 2, 17, 'Беззерновые');
insert into product_types_detailed values (78, 2, 17, 'Паучи');
insert into product_types_detailed values (79, 2, 17, 'Банки консервы');
insert into product_types_detailed values (80, 2, 18, 'Силикагелевый');
insert into product_types_detailed values (81, 2, 18, 'Древесный');
insert into product_types_detailed values (82, 2, 18, 'Комкующийся');
insert into product_types_detailed values (83, 2, 18, 'Впитывающий');
insert into product_types_detailed values (84, 2, 19, 'Витамины и добавки');
insert into product_types_detailed values (85, 2, 19, 'Для выведения шерсти');
insert into product_types_detailed values (86, 2, 19, 'Мясные, вяленые, печеные');
insert into product_types_detailed values (87, 2, 19, 'Сушеные');
insert into product_types_detailed values (88, 2, 19, 'Крем лакомства');
insert into product_types_detailed values (89, 2, 19, 'Колбаски');
insert into product_types_detailed values (90, 2, 19, 'Подушечки');
insert into product_types_detailed values (91, 2, 20, 'Шампуни');
insert into product_types_detailed values (92, 2, 20, 'Уход за шерстью');
insert into product_types_detailed values (93, 2, 20, 'Уход за глазами и ушами');
insert into product_types_detailed values (94, 2, 20, 'Туалеты');
insert into product_types_detailed values (95, 2, 20, 'Гигиена');
insert into product_types_detailed values (96, 2, 20, 'Груминг');
insert into product_types_detailed values (97, 2, 20, 'Когтеточки, когтедралки');
insert into product_types_detailed values (98, 2, 20, 'Комплексы');
insert into product_types_detailed values (99, 2, 21, 'Ошейники');
insert into product_types_detailed values (100, 2, 21, 'Шлейки и поводки');
insert into product_types_detailed values (101, 2, 22, 'Металлические');
insert into product_types_detailed values (102, 2, 22, 'Керамические');
insert into product_types_detailed values (103, 2, 22, 'Пластиковые');
insert into product_types_detailed values (104, 2, 22, 'Двойные');
insert into product_types_detailed values (105, 2, 22, 'Автопоилки и автокормушки');
insert into product_types_detailed values (106, 2, 23, 'Удочки, дразнилки');
insert into product_types_detailed values (107, 2, 23, 'Мышки');
insert into product_types_detailed values (108, 2, 23, 'Мячи');
insert into product_types_detailed values (109, 2, 24, 'Лежаки и лежанки');
insert into product_types_detailed values (110, 2, 24, 'Домики');
insert into product_types_detailed values (111, 2, 25, 'Переноски');
insert into product_types_detailed values (112, 2, 25, 'Сумки');
insert into product_types_detailed values (113, 2, 26, 'Средства от паразитов');
insert into product_types_detailed values (114, 2, 26, 'Для глаз и ушей');
insert into product_types_detailed values (115, 2, 26, 'Ветеринарные аксессуары');
insert into product_types_detailed values (116, 3, 27, 'Для золотых рыб');
insert into product_types_detailed values (117, 3, 27, 'Для декоративных рыб');
insert into product_types_detailed values (118, 3, 27, 'Для тропических рыб');
insert into product_types_detailed values (119, 3, 27, 'Для прудовых рыб');
insert into product_types_detailed values (120, 3, 27, 'Для донных рыб');
insert into product_types_detailed values (121, 3, 27, 'Для цихлид');
insert into product_types_detailed values (122, 3, 27, 'Для гуппи и дискусов');
insert into product_types_detailed values (123, 3, 27, 'Для всех видов рыб');
insert into product_types_detailed values (124, 3, 29, 'Электрооборудование');
insert into product_types_detailed values (125, 3, 29, 'Аквариумистика');
insert into product_types_detailed values (126, 4, 30, 'Для кроликов');
insert into product_types_detailed values (127, 4, 30, 'Для крыс и мышей');
insert into product_types_detailed values (128, 4, 30, 'Для хомяков и морских свинок');
insert into product_types_detailed values (129, 4, 30, 'Для хорьков');
insert into product_types_detailed values (130, 4, 30, 'Для шиншилл');
insert into product_types_detailed values (131, 4, 30, 'Другие грызуны');
insert into product_types_detailed values (132, 4, 30, 'Универсальный для грызунов');
insert into product_types_detailed values (133, 4, 31, 'Витамины');
insert into product_types_detailed values (134, 4, 31, 'Лакомства');
insert into product_types_detailed values (135, 4, 32, 'Клетки');
insert into product_types_detailed values (136, 4, 32, 'Домики и гамаки');
insert into product_types_detailed values (137, 4, 32, 'Миски поилки');
insert into product_types_detailed values (138, 4, 32, 'Туалеты и наполнители');
insert into product_types_detailed values (139, 4, 32, 'Гигиена и химия');
insert into product_types_detailed values (140, 4, 32, 'Груминг');
insert into product_types_detailed values (141, 4, 32, 'Шлейки');
insert into product_types_detailed values (142, 5, 35, 'Для попугаев');
insert into product_types_detailed values (143, 5, 35, 'Для птиц');
insert into product_types_detailed values (144, 5, 38, 'Домики и гнёзда');
insert into product_types_detailed values (145, 5, 38, 'Жердочки');
insert into product_types_detailed values (146, 5, 38, 'Зеркала');
insert into product_types_detailed values (147, 5, 38, 'Купалки');
insert into product_types_detailed values (148, 5, 41, 'Подкормки');
insert into product_types_detailed values (149, 5, 41, 'Минеральные блоки, смеси и гравий');
insert into product_types_detailed values (150, 5, 41, 'Палочки');
insert into product_types_detailed values (151, 5, 41, 'Витамины');
insert into product_types_detailed values (152, 5, 41, 'Лакомства');
insert into product_types_detailed values (153, 5, 42, 'Качели');
insert into product_types_detailed values (154, 5, 42, 'Подвесные игрушки и лестницы');
